### PR TITLE
Adding a <chart> directive and re-factoring chart rendering

### PR DESCRIPTION
**Pull request by mfitz3**

### CODE REVIEW

**Comment by netj** [comment]
README looks great.  Let's attach more commits including the chart directive implementation here and merge it at once.

**Comment by mfitz3** [comment]
This change is dependent on https://github.com/HazyResearch/mindbender/issues/11 being fixed.

**Comment by netj** [comment]
Here are some issues found through testing with calibration plot in #10 
* [ ] num-steps attribute that controls slider visiblity
* [ ] axis-scale attribute for turning logarithmic
* [ ] y-label as series name
* [ ] resize after initial rendering?
* [ ] user defined highcharts-options should be respected

**Comment by mfitz3** [comment]
Above issues have now been fixed. To address the top two points - as discussed, the slider displays all of the raw data when slid completely to the right, and binned categories for any other slide position. On first load, the bar chart displays the raw data, unless there are more than 3^3 values, in which case it is initialized using cubic bins.

**Comment by netj** [comment]
Let's handle the logarithmic axis option later.  Looks good.

**Pull request merged**
